# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='code',
            field=models.CharField(default='sa', max_length=32),
            preserve_default=False,
        ),
    ]
