# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20161217_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosttoapp',
            name='aobj',
        ),
        migrations.RemoveField(
            model_name='hosttoapp',
            name='hobj',
        ),
        migrations.DeleteModel(
            name='HostToApp',
        ),
    ]
